<div class="search-form">
<form method="GET">
		<input type="text" class="search-input" name="search_name" id="search_name" placeholder="Un titre" value=""/>
		<input type="text" class="search-input" name="search_country" id="search_country" placeholder="Un pays" value=""/>
		<label for="yearmin">Année de publication </label>
		<input type="text" class="search-small" name="yearmin" id="yearmin" placeholder="année" /> à
		<input type="text" class="search-small" name="yearmax" id="yearmax" placeholder="année"/>
		<input type="text" class="search-input" name="search_isbn" id="search_isbn" placeholder="ISBN" value="" />
		<input type="text" class="search-input" name="search_editorial" id="search_editorial" placeholder="Une maison d'édition" value=""/>
		<select class="search-input" name="search_gender" id="search_gender" placeholder="Un genre" value="">
			<option value="" selected>Choisissez un genre</option>
						<?php foreach ($genders AS $gender) : ?>
							<option><?=$gender?></option>
						<?php endforeach; ?>
		</select>
		<label for="pricemin">Prix </label><input type="text" class="search-small" placeholder="min" name="pricemin" id="pricemax"/>
		<input type="text" class="search-small" placeholder="max" name="pricemax" id="pricemax"/>
		<input type="submit" class="search-button" value="Rechercher">
	</form>
</div>