<div class="results">
	
	<img class="float-left" src="./public/img/book.svg" width="80px" alt="">
	<div class="descriptions">
		<h2><?=$books->getName()?></h2>
		<h2><?=$books->getId()?></h2>
		<div class="clearfix"></div>
		<h4><span><?=$books->getAuthor()?></span> - <?=$books->getCountry()?> - <?=$books->getYear()?></h4>
		<h3><?=$books->getIsbn()?></h3>
		<p><?=$books->getCountry()?></p>
		<p><?=$books->getPrice()?></p>
	</div>
	<div class="clearfix"></div>
</div>